version: '3'

services:
    envoy:
        image: envoyproxy/envoy:v1.27.2
        ports:
            - '8080:8080'
        volumes:
            - ./envoy.yaml:/etc/envoy/envoy.yaml
        depends_on:
            - echo1
            - echo2
            - echo3
    echo1:
        container_name: echo1
        image: jmalloc/echo-server
        expose:
            - 8080
    echo2:
        container_name: echo2
        image: jmalloc/echo-server
        expose:
            - 8080
    echo3:
        container_name: echo3
        image: jmalloc/echo-server
        expose:
            - 8080
